import 'package:proyecto_intermodular/models/ModeloEquipo.dart';
import 'package:proyecto_intermodular/models/ModeloJugador.dart';
import 'package:proyecto_intermodular/models/liga.dart';

class Modeloligaespecial extends Liga {
  final List<Modeloequipo> listaSelecciones = [
    Modeloequipo(
      nombre: 'México',
      usuario: null,
      equipo: [],
      escudo: 'images/logoMexico.png',
    ),
    Modeloequipo(
      nombre: 'Sudafrica',
      usuario: null,
      equipo: [],
      escudo: 'images/logoSudafrica.png',
    ),
    Modeloequipo(
      nombre: 'Corea Del Sur',
      usuario: null,
      equipo: [],
      escudo: 'images/logoCorea.png',
    ),
    Modeloequipo(
      nombre: 'Republica Checa',
      usuario: null,
      equipo: [],
      escudo: 'images/logoRepublicaCheca.png',
    ),
    Modeloequipo(
      nombre: 'Canadá',
      usuario: null,
      equipo: [],
      escudo: 'images/logoCanada.png',
    ),
    Modeloequipo(
      nombre: 'Bosnia y Herzegovina',
      usuario: null,
      equipo: [
        Modelojugador(
          id_jugador: 1,
          nombre: "Nikola Vasijl",
          pais: "images/logoBosnia.png",
          valor_clausula: 14000000,
          valor_venta: 4000000,
          posicion: "POR",
        ),
        Modelojugador(
          id_jugador: 2,
          nombre: "Martin Zlomislic",
          pais: "images/logoBosnia.png",
          valor_clausula: 8000000,
          valor_venta: 1000000,
          posicion: "POR",
        ),
        Modelojugador(
          id_jugador: 3,
          nombre: "Sead Kolasinac",
          pais: "images/logoBosnia.png",
          valor_clausula: 18000000,
          valor_venta: 6000000,
          posicion: "DEF",
        ),
        Modelojugador(
          id_jugador: 4,
          nombre: "Tarik Muharemovic",
          pais: "images/logoBosnia.png",
          valor_clausula: 40000000,
          valor_venta: 20000000,
          posicion: "DEF",
        ),
        Modelojugador(
          id_jugador: 5,
          nombre: "Amar Dedic",
          pais: "images/logoBosnia.png",
          valor_clausula: 38000000,
          valor_venta: 18000000,
          posicion: "DEF",
        ),
         Modelojugador(
          id_jugador: 6,
          nombre: "Nikola Katic",
          pais: "images/logoBosnia.png",
          valor_clausula: 8000000,
          valor_venta: 2000000,
          posicion: "DEF",
        ),
        Modelojugador(
          id_jugador: 7,
          nombre: "Benjamin Tahirovic",
          pais: "images/logoBosnia.png",
          valor_clausula: 12000000,
          valor_venta: 4000000,
          posicion: "CEN",
        ),
        Modelojugador(
          id_jugador: 8,
          nombre: "Amar Memic",
          pais: "images/logoBosnia.png",
          valor_clausula: 12000000,
          valor_venta: 4000000,
          posicion: "CEN",
        ),
        Modelojugador(
          id_jugador: 9,
          nombre: "Amir Hadziahmetovic",
          pais: "images/logoBosnia.png",
          valor_clausula: 12000000,
          valor_venta: 4000000,
          posicion: "CEN",
        ),
        Modelojugador(
          id_jugador: 10,
          nombre: "Ermedin Demirovic",
          pais: "images/logoBosnia.png",
          valor_clausula: 42000000,
          valor_venta: 22000000,
          posicion: "DEL",
        ),
        Modelojugador(
          id_jugador: 11,
          nombre: "Haris Tabakovic",
          pais: "images/logoBosnia.png",
          valor_clausula: 11000000,
          valor_venta: 3000000,
          posicion: "DEL",
        ),
        Modelojugador(
          id_jugador: 12,
          nombre: "Edin Dzeko",
          pais: "images/logoBosnia.png",
          valor_clausula: 10000000,
          valor_venta: 2000000,
          posicion: "DEL",
        ),
      ],
      escudo: 'images/logoBosnia.png',
    ),
    Modeloequipo(
      nombre: 'Catar',
      usuario: null,
      equipo: [],
      escudo: 'images/logoCatar.png',
    ),
    Modeloequipo(
      nombre: 'Suiza',
      usuario: null,
      equipo: [],
      escudo: 'images/logoSuiza.png',
    ),
    Modeloequipo(
      nombre: 'Brasil',
      usuario: null,
      equipo: [],
      escudo: 'images/logoBrasil.png',
    ),
    Modeloequipo(
      nombre: 'Marruecos',
      usuario: null,
      equipo: [],
      escudo: 'images/logoMarruecos.png',
    ),
    Modeloequipo(
      nombre: 'Haiti',
      usuario: null,
      equipo: [],
      escudo: 'images/logoHaiti.png',
    ),
    Modeloequipo(
      nombre: 'Escocia',
      usuario: null,
      equipo: [],
      escudo: 'images/logoEscocia.png',
    ),
    Modeloequipo(
      nombre: 'Estados Unidos',
      usuario: null,
      equipo: [],
      escudo: 'images/logoUSA.png',
    ),
    Modeloequipo(
      nombre: 'Paraguay',
      usuario: null,
      equipo: [],
      escudo: 'images/logoParaguay.png',
    ),
    Modeloequipo(
      nombre: 'Australia',
      usuario: null,
      equipo: [],
      escudo: 'images/logoAustralia.png',
    ),
    Modeloequipo(
      nombre: 'Turquía',
      usuario: null,
      equipo: [],
      escudo: 'images/logoTurquia.png',
    ),
    Modeloequipo(
      nombre: 'Alemania',
      usuario: null,
      equipo: [],
      escudo: 'images/logoAlemania.png',
    ),
    Modeloequipo(
      nombre: 'Curazao',
      usuario: null,
      equipo: [],
      escudo: 'images/logoCurazao.png',
    ),
    Modeloequipo(
      nombre: 'Costa de Marfil',
      usuario: null,
      equipo: [],
      escudo: 'images/logoMarfil.png',
    ),
    Modeloequipo(
      nombre: 'Ecuador',
      usuario: null,
      equipo: [],
      escudo: 'images/logoEcuador.png',
    ),
    Modeloequipo(
      nombre: 'Países Bajos',
      usuario: null,
      equipo: [],
      escudo: 'images/logoHolanda.png',
    ),
    Modeloequipo(
      nombre: 'Japon',
      usuario: null,
      equipo: [],
      escudo: 'images/logoJapon.png',
    ),
    Modeloequipo(
      nombre: 'Suecia',
      usuario: null,
      equipo: [],
      escudo: 'images/logoSuecia.png',
    ),
    Modeloequipo(
      nombre: 'Tunez',
      usuario: null,
      equipo: [],
      escudo: 'images/logoTunez.png',
    ),
    Modeloequipo(
      nombre: 'Belgica',
      usuario: null,
      equipo: [],
      escudo: 'images/logoBelgica.png',
    ),
    Modeloequipo(
      nombre: 'Egipto',
      usuario: null,
      equipo: [],
      escudo: 'images/logoEgipto.png',
    ),
    Modeloequipo(
      nombre: 'Iran',
      usuario: null,
      equipo: [],
      escudo: 'images/logoIran.png',
    ),
    Modeloequipo(
      nombre: 'Nueva Zelanda',
      usuario: null,
      equipo: [],
      escudo: 'images/logoNuevaZel.png',
    ),
    Modeloequipo(
      nombre: 'España',
      usuario: null,
      equipo: [],
      escudo: 'images/logoEspana.png',
    ),
    Modeloequipo(
      nombre: 'Cabo Verde',
      usuario: null,
      equipo: [],
      escudo: 'images/logoCabo.png',
    ),
    Modeloequipo(
      nombre: 'Arabia Saudita',
      usuario: null,
      equipo: [],
      escudo: 'images/logoArabia.png',
    ),
    Modeloequipo(
      nombre: 'Uruguay',
      usuario: null,
      equipo: [],
      escudo: 'images/logoUruguay.png',
    ),
    Modeloequipo(
      nombre: 'Francia',
      usuario: null,
      equipo: [],
      escudo: 'images/logoFrancia.png',
    ),
    Modeloequipo(
      nombre: 'Senegal',
      usuario: null,
      equipo: [],
      escudo: 'images/logoSenegal.png',
    ),
    Modeloequipo(
      nombre: 'Irak',
      usuario: null,
      equipo: [],
      escudo: 'images/logoIrak.png',
    ),
    Modeloequipo(
      nombre: 'Noruega',
      usuario: null,
      equipo: [],
      escudo: 'images/logoNoruega.png',
    ),
    Modeloequipo(
      nombre: 'Argentina',
      usuario: null,
      equipo: [],
      escudo: 'images/logoArgentina.png',
    ),
    Modeloequipo(
      nombre: 'Argelia',
      usuario: null,
      equipo: [],
      escudo: 'images/logoArgelia.png',
    ),
    Modeloequipo(
      nombre: 'Austria',
      usuario: null,
      equipo: [],
      escudo: 'images/logoAustria.png',
    ),
    Modeloequipo(
      nombre: 'Jordania',
      usuario: null,
      equipo: [],
      escudo: 'images/logoJordania.png',
    ),
    Modeloequipo(
      nombre: 'Portugal',
      usuario: null,
      equipo: [],
      escudo: 'images/logoPortugal.png',
    ),
    Modeloequipo(
      nombre: 'RD Congo',
      usuario: null,
      equipo: [],
      escudo: 'images/logoCongo.png',
    ),
    Modeloequipo(
      nombre: 'Uzbekistán',
      usuario: null,
      equipo: [],
      escudo: 'images/logoUzbekistan.png',
    ),
    Modeloequipo(
      nombre: 'Colombia',
      usuario: null,
      equipo: [],
      escudo: 'images/logoColombia.png',
    ),
    Modeloequipo(
      nombre: 'Inglaterra',
      usuario: null,
      equipo: [],
      escudo: 'images/logoInglaterra.png',
    ),
    Modeloequipo(
      nombre: 'Croacia',
      usuario: null,
      equipo: [],
      escudo: 'images/logoCroacia.png',
    ),
    Modeloequipo(
      nombre: 'Ghana',
      usuario: null,
      equipo: [],
      escudo: 'images/logoGhana.png',
    ),
    Modeloequipo(
      nombre: 'Panama',
      usuario: null,
      equipo: [],
      escudo: 'images/logoPanama.png',
    ),
  ];

  Modeloligaespecial({
    required super.id_liga,
    required super.cod_invitacion,
    required super.propietario,
    required super.nombreLiga,
  });
}
